import { StyleSheet } from "react-native";
import {COLORS, SIZES} from "../constants/index";

const styles = StyleSheet.create({
    container:{
        flex:1
    },
    upperRow:{
        marginHorizontal:20,
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        position:"absolute",
        width:SIZES.width-44,
        zIndex:999
    },
    image:{
        marginTop:40,
        height:250,
        width:250,
        alignSelf:"center"
    },
    details:{
        marginTop: -SIZES.large,
        backgroundColor:COLORS.lightWhite,
        width:SIZES.width,
        borderTopLeftRadius:SIZES.medium,
        borderTopRightRadius:SIZES.medium
    },
    titleRow:{
        marginHorizontal:20,
        paddingBottom:SIZES.small,
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        width:SIZES.width-44,
        top:20
    },
    priceWrapper:{
        backgroundColor:COLORS.secondary,
        borderRadius:SIZES.large
    },
    title:{
        fontFamily:"bold",
        fontSize:SIZES.large
    },
    price:{
        paddingHorizontal:6,
        fontFamily:"semibold",
        fontSize:SIZES.large
    },
    ratingRow:{
        top:5,
        width:SIZES.width-10,
        justifyContent:"space-between",
        flexDirection:"row",
        paddingBottom:SIZES.small,
        alignItems:"center"
    },
    rating:{
        top:SIZES.large,
        flexDirection:"row",
        justifyContent:"flex-start",
        alignItems:"center",
        marginHorizontal:SIZES.large
    },
    ratingText:{
        color:COLORS.gray,
        fontFamily:"medium",
        marginLeft:SIZES.xLarge+9
    },
    descriptionWrapper:{
        marginTop:SIZES.large *2,
        marginLeft:SIZES.large,
    },
    description:{
        fontFamily:"medium",
        fontSize:SIZES.large-2
    },
    descText:{
        fontFamily:"regular",
        fontSize:SIZES.small,
        textAlign:"justify",
        marginBottom:SIZES.small
    },
    location:{
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        backgroundColor:COLORS.secondary,
        marginHorizontal:12,
        padding:5,
        borderRadius:SIZES.large
    },
    cartRow:{
        paddingBottom:SIZES.small,
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        width:SIZES.width - 44,
        top:20
    },
    cartBtn:{
        width:SIZES.width*0.7,
        backgroundColor:COLORS.black,
        borderRadius:SIZES.large,
        marginLeft:12,
        padding:SIZES.small
    },
    cartTitle:{
        color:COLORS.lightWhite,
        fontSize:SIZES.medium,
        alignSelf:"center"
    },
    addCart:{
        width:47,
        height:37,
        borderRadius:50,
        marginLeft:47,
        alignItems:"center",
        justifyContent:"center",
        backgroundColor:COLORS.black
    }
})

export default styles;